query getPost($id: ID) {
  post(where: {id: $id}) {
    status
    updatedAt
    createdAt
    id
    title
    content
    description
    thumbnail {
      status
      updatedAt
      createdAt
      id
      handle
      fileName
      height
      width
      size
      mimeType
    }
    category
  }
}
